### ISSUE TITLE
lmdbg-sym argument confusion

### ISSUE THREAD

**Issue by gson1703** [cheusov/lmdbg#1]
There seems to be some discrepancies in the lmdbg documentation as to
whether the lmdbg-sym script takes the program as its first argument
or not.

lmdbg-1.3.0/README seems to imply that it does:

    user@host$ lmdbg-sym PROG \
        < /tmp/PROG.log2 > /tmp/PROG_LEAKS_SRC.log3

and so does the lmdbg-leaks man page:

    lmdbg-sym ./my_app log_leaks > log_leaks2 &&

but according to the lmdbg-sym man page, or from my reading of the
script itself, it doesn't.

**Comment by cheusov** [comment]
Fixed in e3943d6. Thanks!
